### ISSUE TITLE
Please add a clear description of what youtube-cue does and the requirements for a youtube-video in order to work

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#60]
## My intention is this
- I download a DJ mix published on Youtube.
- Somewhere in the description is a tracklisting with timecodes.
- When triggering youtube-cue <URL> <output.cue> it downloads the metadata and runs a parser.
- If that parser finds sufficient metadata it creates an output.cue
- Then by help of other tools you download the audio track of a given youtube-URL, and according to the cue-sheet which youtube-cue produced, those tools cut the large mix down into the individual tracks, and individually change their filename and metadata (ID3).

## Is this the intended purpose?
From the given name and description it sounds like that, but it is not explicitly telling this.
A clearer description would be appreciated.

**Comment by captn3m0** [comment]
Yes, this is the exact purpose. I'll clarify the README a bit.
