### ISSUE TITLE
How do I get the debug log for youtube-cue ?

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#61]
readme.md states:
> If this video does not work on a specific video, please attach the debug log output.

But how do I get the debug?
- `--help` does not tell me
- there isn't a **manpage** 
- and also nothing in that regard in **readme.md**

**Comment by captn3m0** [comment]
Sorry, the README is a bit [forward-sounding](https://tom.preston-werner.com/2010/08/23/readme-driven-development.html).

**Comment by captn3m0** [comment]
Closing for now, don't have plans for debug output. Removed from the README.
