### ISSUE TITLE
youtu.be shortlink support

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#62]
Does youtube-cue support `youtu.be/videoID` shortlinks?
- If yes, please mention it in the --help and in readme.md
- If no, would be cool if support could be added.

**Comment by captn3m0** [comment]
Short links are supported - I hadn't tested for it, but they seem to work.

I just pushed a new release (1.0.3), can you upgrade and test please? It seems to work for me.

    npm update -g youtube-cue

**Comment by captn3m0** [comment]
Added note in README and examples for this. Closing
