### ISSUE TITLE
youtube-cue not working for a DJ mix which has a tracklist in its description

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#63]
## Input
https://youtu.be/Yir4WyDi8rU is a DJ mix with a tracklist embedded somwhere in its description text. Structurally like this:
```
Some paragraphs of text. […]

Tracklist: 
[00:00:00] 1. Artist - Title
[00:02:53] 2. Artist - Title
[00:05:55] 3. Artist - Title
[00:08:49] 4. Artist - Title
[…]
```

## Environment
macOS 11.4
youtube-cue 1.0.2

## Attempts
I tried 3 different syntaxes (full youtube.com URL vs youtu.be short URL) and ("mix.cue" vs. literal "output.cue" as stated in --help)
```
test-yt-dl youtube-cue --audio-file "https://youtu.be/Yir4WyDi8rU" mix.cue
test-yt-dl youtube-cue --audio-file "https://youtube.com/watch?v=Yir4WyDi8rU" mix.cue 
test-yt-dl youtube-cue --audio-file "https://youtube.com/watch?v=Yir4WyDi8rU" output.cue
```

## Expected
I get the cue-sheet or an error message which explains me why youtube-cue could not create a cue-sheet.

## Actual
The result is always that the command line produces nothing but only outputs the "Usage" instructions. The same ones you get with --help.

## Afterword
- Excellent communication & support by the developer! As I am writing this issue, the previous three issues were already answered! So less speculation, more concrete, wonderful!
  - The app is supposed to support exactly that use case as confirmed by #60 
  - There is no debug option yet according to #61 so what's above is all the input that I can provide for now.
  - Shortlinks are confirmed to be supported by #62
- Will try to update to 1.0.3 and see if it works then.

**Comment by porg** [comment]
- Updated to 1.0.3 — Still not working
- I see no network connection made by youtube-cue on my Network Monitor. So I think it fails very early. But without output It's hard to tell where/how it fails.

**Comment by captn3m0** [comment]
The `--audio-file` parameter is for specifying the audio filename that goes in the CUE file. Running `youtube-cue  "https://youtu.be/Yir4WyDi8rU" mix.cue` does generate a valid CUE sheet:

```cue
REM Generated using youtube-cue
PERFORMER "Spinnin' Records"
TITLE "160 BPM | Best Running Music"
FILE "Running Mix 2020 | 135 - 160 BPM | Best Running Music.m4a" M4A
  TRACK 1 AUDIO
    TITLE "] 1. Steve Kroeger x Skye Holland - Through The Dark "
    PERFORMER "] 1. Steve Kroeger x Skye Holland"
    INDEX 01 0:0:00
```

It is a bit broken, because youtube-cue doesn't support timestamps in square brackets yet. TODO:

- [ ] #64
- [x] Improve README and `--help`

**Comment by porg** [comment]
1. Can confirm with the misunderstanding regarding `--audio-file` clarified downloading and parsing now work.
2. The `--help` message is irritating as it contradicts common command line conventions. Please change it to this:
> youtube-cue [--audio-file "Desired Music File Name.suffix"] <youtube_url> <output.cue>

Rationale: The --audio-file parameter in brackets to indicate that it's optional.

Later in the help text please add an explanation 

> --audio-file "Desired Music File Name.suffix" Optional. If unspecified then youtube-dl will use the title of the Youtube URL with whitespace and no character escaping as the filename and the file suffix according to of the best audio track it encounters, i.e. "m4a".

3. If the user provides an invalid input syntax (as I did unknowingly) then please throw an explicit error message followed by the "Usage" text. Otherwise you don't know "Is just the program malfunctioning or was my input insufficient?". Thanks.

**Comment by captn3m0** [comment]
Already changed, but needs a new release: https://github.com/captn3m0/youtube-cue/commit/f00efc7806cd1e228676e2d4e121ab29f25df551#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

The suffix is hardcoded currently, I want to make it follow `youtube-dl`'s  template convention down the line.

**Comment by captn3m0** [comment]
>please throw an explicit error message

Thanks for this suggestion

**Comment by porg** [comment]
> The suffix is hardcoded currently

Good to know. Am not sure that youtube really uses AAC audio everywhere, especially not sure for elder youtube videos.

> I want to make it follow `youtube-dl`'s template convention down the line.

Now it turns out that I was forward-sounding 😉 with my proposed manpage addition too:

> youtube-dl will use […] the file suffix according to of the best audio track it encounters, i.e. "m4a"

But good to know that that's planned.

For now it would be good if `--help` mentions that "m4a" is hardcoded and that it will be AAC most time anyways, but in some cases maybe not. In those cases you must correct your file suffix manually.

**Comment by captn3m0** [comment]
Checking for valid filenames is tricky, because URLs are technically valid filenames.

```
path.resolve('https://youtube.com/watch?v=Yir4WyDi8rU')
'/a/b/c/https:/youtube.com/watch?v=Yir4WyDi8rU'
path.basename('https://youtube.com/watch?v=Yir4WyDi8rU')
'watch?v=Yir4WyDi8rU'
```

**Comment by captn3m0** [comment]
Since the original URL now parses correctly, closing this ticket. Will create a new issue for warning about bad filenames for `audio-file` argument.
