### ISSUE TITLE
Are tracks in a generated CUE sheet supposed to have START timestamps only or also END and DURATION ?

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#66]
https://www.youtube.com/watch?v=Yir4WyDi8rU produces this CUE sheet: [Running Mix 2020 135-160 BPM.cue.txt](https://github.com/captn3m0/youtube-cue/files/6725402/Running.Mix.2020.135-160.BPM.cue.txt)

## When opening the MP3/CUE pair in VLC media player
- Initially only the first track shows a duration.
- When skipping through the tracks, the other tracks also update their duration info,
- But those durations are all wrong, the duration of the individual tracks is falsely always the duration of the entire mix.
<img width="360" alt="Track start end duration - VLC playback init" src="https://user-images.githubusercontent.com/737143/123622036-1183f580-d80c-11eb-9ac3-ad917db6365b.png"> <img width="360" alt="Track start end duration - VLC playback later" src="https://user-images.githubusercontent.com/737143/123622050-15b01300-d80c-11eb-90d0-a3a753650203.png">

## Now these raises the following questions
- A proper CUE sheet, is it supposed to have START END DURATION time info for each track?
  -  Logical thinking deduces this would be optimal, because then this info would be ready right after the player has read in the file
  - Of course END + DURATION of all songs but the last can easily be calculcated by substraction and addition.
  - But the last track END and DURATION would need to be calculcated against the length of the entire mix
    - either specified in the CUE sheet
    - or read out from the length of the audio file (UI needs to await processing of the media player first)
- Or is the media player supposed to to that calculations?

## Followup
- If it is alright as it is (START only), then I may submit this as a bug/feature-proposal to VLC.
- If a CUE sheet should have START END DURATION per each track, than youtube-cue should optimally do those calculations, and embedd that into the CUE sheet.

**Comment by captn3m0** [comment]
Do you have a doc for the START/END/DURATION part? I used [Wikipedia](https://en.wikipedia.org/wiki/Cue_sheet_(computing)#Essential_commands) which refers the following as sources:

- https://web.archive.org/web/20160201021136/http://digitalx.org/cue-sheet/syntax/#indx
- https://wiki.hydrogenaud.io/index.php?title=Cue_sheet

None of these mention a duration or END time, so I think it is left to the player.

**Comment by porg** [comment]
✅ Closing:
- Looked through your provided specs and also searched a bit beyond that.
- Found no indication for the attributes END or DURATION.
- Seems ok as-is.
  - What can be seen on the screenshots is likely a bug of VLC.
  - mp3split splits just fine with only START being provided per track.
