### ISSUE TITLE
Support tracklists with durations + arbitrary position of duration and tracknumber

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#68]
Some tracklist come in this format:

```
TRACKLIST
1. Artist - Title - 6:19
2. Another Artist - Another Title - 6:59
3. Yet Another Artist - Yet another title - 5:12
```

In the majority of situations one can programmatically recognize that the given times are not points-in-time (indices) but durations, by checking these criteria:
1. The first timestamp does not start at 00:00:00 or anywhere near it
 (given the offset of a few seconds which can sometimes occur due to gap corrections)
2. If we have indeed point-in-times then the next track always must have a higher point-in-time. If it are durations it could be coincidence that each track is always a bit longer than the previous one. But statistically very unlikely. As soon as there are a few tracks on an album very very likely always one will be shorter than any of the previous songs. If only a single track is shorter than any previous one, we can be sure that these are durations rather than point-in-times.

So an algorithm should almost always auto-detect.
If not we could throw back an interactive question to the shell, and let the user decide.
> **Error**: Could not automatically interpret the given timestamps.
> Are these (p)oints-in-time or (d)urations ?
$ _

**Comment by porg** [comment]
If youtube-cue gets a more generalized tool (see #67 ) then detecting the not so uncommon format (track duration rather than point-in-time) would be very handy!

**Comment by captn3m0** [comment]
Do you have a few example sources for this? I know tracklists in musicbrainz (and other DB sites) might follow this, but there you'd usually have existing tools to generate cue files.

I'll have to think about implementing this (perhaps with a `--timestamps-are-durations` flag) but seeing some references would make this easier.

**Comment by porg** [comment]
[LTJ&Conrad-ProgressionSessions1.txt](https://github.com/captn3m0/youtube-cue/files/6727347/LTJ.Conrad-ProgressionSessions1.txt)

**Comment by porg** [comment]
Cool would be if the app is so clever to only need `--timestamps-are-durations` as an enforcement-flag for a non-interactive mode (unattended for batch processing) but by default running interactively with the algorithm being clever enough to get it right in 95% of the time and only if in doubt asking for "Interpret timestamps as points-in-time or durations"?

**Comment by captn3m0** [comment]
Yeah, sounds feasible.

**Comment by captn3m0** [comment]
@porg Do you have suggestions for what the opposite flag should be called? I'm using `--timestamps-only` but I don't like it much. This is the tentative helptext:

```
    --timestamps-only Do not try to parse the timestamps as track durations
    --timestamps-are-durations Parse timestamps as durations

    The above 2 are only needed to force behaviour in very specific edge cases, they should
    not be required for most files.
```

**Comment by captn3m0** [comment]
The code is mostly functional at #72. It uses the simple heuristic of expecting "ascending starting timestamps". If timestamps are not strictly ascending, it switches to duration mode.

Seems to work fine.

**Comment by porg** [comment]
1) Text proposal:
```
Interpretation of numerical values
  Generally the parser detects whether numbers are positional timestamps or track durations.
  To enforce a desired interpretation you can use these flags:
    --timestamps    Parse as positional timestamps (relative to the start of the playlist)
    --durations   Parse timestamps as track durations
```

2) Algorithm: Interpret as timestamps: "Timestamps are ascending" as the only criterium. Let's add one more criterium to be absolutely sure to avoid a false positive. If the numbers are ascending, i.e. "01:00" "02:00" and "03:00" and the "first track is NOT 00:00" then these are indeed durations, just conincidencially songs getting longer and longer later in the playlist. Ok?

**Comment by captn3m0** [comment]
Published these changes as 1.0.6-beta.0 on NPM.

Could you install it and try it out?

`npm install --global youtube-cue@1.0.6-beta.0`

**Comment by porg** [comment]
1) I upgraded to 1.0.6-beta.0
2) Worked with https://www.youtube.com/watch?v=ENqiJKGT20Q which had a timestamp format yet not seen by my:
- Start1 - End1 Track1Name
- Start2 - End2 Track2Name
3) Does **youtube-cue** already work with `file.txt` input?
The tracklists with the durations instead of timestamps I only have as `.TXT` files.
Did yet not encounter it on Youtube.
I do not own a youtube channel to which I could upload a test video with the proper description text.

**Comment by captn3m0** [comment]
Was hoping you'd have a youtube video. I'll upload something and test it out for now.

I'll keep the "timestamps longer-than-video" as a separate issue.

**Comment by porg** [comment]
Ok.

**Comment by porg** [comment]
Already created #75 for your.

**Comment by captn3m0** [comment]
Tested against https://www.youtube.com/watch?v=nhOXFjpK_pc

Seems to work.

**Comment by porg** [comment]
Worked for me too.

https://www.youtube.com/watch\?v\=nhOXFjpK_pc
Has this description text:
```
1:00 Someone - Under the Sea
2:00 Down - Below Water
1:50 Mermaid - Siren of the Sea
3:15 Water - Doesn't get drunk
```

➜  ~ cd ~/Downloads 

➜  Downloads youtube-cue https://www.youtube.com/watch\?v\=nhOXFjpK_pc
"Sample Video.cue" saved

➜  Downloads cat Sample\ Video.cue
```
REM Generated using youtube-cue
PERFORMER "undefined"
TITLE "Sample"
FILE "Sample Video.m4a" M4A
  TRACK 1 AUDIO
    TITLE "Under the Sea"
    PERFORMER "Someone"
    INDEX 01 0:0:00
  TRACK 2 AUDIO
    TITLE "Below Water"
    PERFORMER "Down"
    INDEX 01 1:0:00
  TRACK 3 AUDIO
    TITLE "Siren of the Sea"
    PERFORMER "Mermaid"
    INDEX 01 3:0:00
  TRACK 4 AUDIO
    TITLE "Doesn't get drunk"
    PERFORMER "Water"
    INDEX 01 4:50:00
```
