### ISSUE TITLE
Compliments to the maintainer!

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#69]
@captn3m0 my compliments to you! 👍👍👍 
Our feedback session today was very productive and felt very fulfilling to me!
- Immediate response, immediate fixing: That feels very rewarding for someone providing input!
- Good style of writing: Clear, concise, tags, followups.
  Also here: You know what's in scope, what not, and how things will continue! Very rewarding and motivating!

Thanks for your software and your great community support!

**Comment by captn3m0** [comment]
Thanks a lot for the kind words 😊
