### ISSUE TITLE
Add leading zeroes to all timestamps

### ISSUE THREAD

**Issue by porg** [captn3m0/youtube-cue#74]
1) Leading zeros for single digit numbers.
2) If a tracklist is over 1 hour, then use HH:MM:SS:MS instead of increasing minutes to above 60.

**Comment by captn3m0** [comment]
CUE files actually don't permit `HH` to be used, from what I understand.

Leading zeroes definitely need fixing.

**Comment by porg** [comment]
Ok, you make the best of my proposal! 😉

**Comment by captn3m0** [comment]
Thanks for creating the issue 🥇.
